# Generated by Django 3.2 on 2023-11-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donarsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('Blood_group', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('phoneno', models.IntegerField(default=0)),
            ],
        ),
    ]
