# Generated by Django 3.2 on 2023-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Spaceship', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('Price', models.IntegerField(default=100)),
            ],
        ),
    ]
