# Generated by Django 3.2 on 2023-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oceans', models.CharField(max_length=250)),
                ('lenght', models.IntegerField()),
                ('depth', models.IntegerField()),
            ],
        ),
    ]
