# Generated by Django 3.2 on 2023-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountholdername', models.CharField(max_length=500)),
                ('branchaname', models.CharField(max_length=250)),
                ('accountnumber', models.IntegerField(default=0)),
            ],
        ),
    ]
