# Generated by Django 3.2 on 2023-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('ROM', models.IntegerField()),
                ('RAM', models.IntegerField()),
                ('Processor', models.CharField(max_length=250)),
            ],
        ),
    ]
