# Generated by Django 3.2 on 2023-11-03 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='al',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ali', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='venus.alien')),
            ],
        ),
    ]
