# Generated by Django 3.2 on 2023-11-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pandasp', '0008_alter_products_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pandasp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pandasp.products')),
            ],
        ),
    ]
