# Generated by Django 3.2 on 2023-11-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplainantName', models.CharField(max_length=250)),
                ('ComplainantID', models.IntegerField(default=0)),
                ('ComplaintNumber', models.IntegerField(default=0)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('State', models.CharField(max_length=250)),
                ('Category', models.CharField(max_length=250)),
                ('SubCategory', models.CharField(max_length=250)),
                ('ComplaintDetails', models.TextField()),
            ],
        ),
    ]
