# Generated by Django 3.2 on 2023-11-01 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandasp', '0003_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 1, 22, 22, 0, 660684))),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
