# Generated by Django 3.2 on 2023-11-02 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandasp', '0004_auto_20231101_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 8, 36, 8, 42045)),
        ),
    ]
