# Generated by Django 3.2 on 2023-11-02 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandasp', '0006_alter_products_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 8, 45, 33, 452121)),
        ),
    ]
