# Generated by Django 3.2 on 2023-11-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='Rating',
            field=models.IntegerField(),
        ),
    ]
