# Generated by Django 3.2 on 2023-11-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20231101_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='Price',
            field=models.IntegerField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='Rating',
            field=models.IntegerField(max_length=250),
        ),
    ]
