# Generated by Django 3.2 on 2023-11-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20231103_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productslist')),
            ],
        ),
    ]
