# Generated by Django 3.2 on 2023-11-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productlist')),
            ],
        ),
    ]
