# Generated by Django 3.2 on 2023-11-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rename_title_productlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productlist')),
            ],
        ),
    ]
