# Generated by Django 3.2 on 2023-11-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
