# Generated by Django 3.2 on 2023-11-02 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField(max_length=250)),
                ('rating', models.IntegerField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2023, 11, 2, 9, 16, 19, 872839))),
            ],
        ),
    ]
