# Generated by Django 3.2 on 2023-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='milage',
            field=models.IntegerField(default=50),
        ),
    ]
