# Generated by Django 3.2.22 on 2023-11-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='tating',
            new_name='rating',
        ),
    ]
