# Generated by Django 3.2 on 2023-11-02 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 9, 19, 15, 608140)),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
