# Generated by Django 3.2 on 2023-11-01 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 17, 0, 17, 992496)),
        ),
    ]
