# Generated by Django 3.2 on 2023-11-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='model',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
