# Generated by Django 3.2 on 2023-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
