# Generated by Django 3.2 on 2023-11-01 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 17, 39, 15, 511474)),
        ),
        migrations.AddField(
            model_name='productslist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productslist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
