# Generated by Django 3.2 on 2023-11-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlist_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='models',
            new_name='model',
        ),
    ]
