# Generated by Django 3.2 on 2023-11-01 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231101_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
