# Generated by Django 3.2 on 2023-10-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productslist_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productslist',
            old_name='title',
            new_name='name',
        ),
    ]
