# Generated by Django 3.2.22 on 2023-11-06 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_tating_productlist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='created_by',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
