# Generated by Django 3.2 on 2023-11-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlist_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='title',
            new_name='name',
        ),
    ]
