# Generated by Django 3.2 on 2023-11-01 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231101_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='milage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productslist',
            name='model',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 18, 9, 37, 942485)),
        ),
    ]
