# Generated by Django 3.2 on 2023-11-01 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231101_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('model', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('milage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 1, 21, 58, 52, 227191))),
            ],
        ),
        migrations.DeleteModel(
            name='ProductsList',
        ),
    ]
