# Generated by Django 3.2 on 2023-11-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_models_productlist_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='model',
            new_name='modelname',
        ),
    ]
