# Generated by Django 3.2 on 2023-11-02 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231101_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 8, 19, 33, 236175)),
        ),
    ]
