# Generated by Django 3.2 on 2023-11-01 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productslist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 18, 10, 11, 950667)),
        ),
    ]
